version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/var/www/html/uploads 
      - .:/var/www/html 
    ports:
      - 8080:80
    command: >
      bash -c "chown -R www-data:www-data /var/www/html/uploads && 
               chmod -R 775 /var/www/html/uploads && 
               apache2-foreground"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/query.sql:/docker-entrypoint-initdb.d/query.sql

volumes:
  postgres_data:
