version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/var/www/html/uploads 
      - .:/var/www/html 
    ports:
      - 8080:80
    command: >
      bash -c "chown -R www-data:www-data /var/www/html/uploads && 
               chmod -R 775 /var/www/html/uploads && 
               apache2-foreground"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Database/query.sql:/docker-entrypoint-initdb.d/query.sql

volumes:
  mysql_data:
